export const shopConstants = {
    GET_AUTHOR: 'GET_AUTHOR',
    GET_CATEGORY: 'GET_CATEGORY',
    GET_STAR: 'GET_STAR',
    GET_BOOK_DEFAULT: 'GET_BOOK_DEFAULT',
    GET_BOOK_ID: 'GET_BOOK_ID',
    GET_SHOW: 'GET_SHOW',
<<<<<<< HEAD
    UPDATE_FILTER_PARAMS: 'UPDATE_FILTER_PARAMS',
    UPDATE_LAST_PAGINATION: 'UPDATE_LAST_PAGINATION',
    UPDATE_CURRENT_PAGINATION: 'UPDATE_CURRENT_PAGINATION'
=======
    UPDATE_FILTER_PARAMS: 'UPDATE_FILTER_PARAMS'
>>>>>>> d9685d60ef33f6005776fca24a3d3bf39cd54703
}
